name: Sync New Keys and Values to Translations
# Trigger the workflow on pushes to main that modify the base messages file,
# and allow for manual dispatch.
on:
  workflow_dispatch:
  push:
    branches: [main,annazhang-fix-workflow-to-sync-translation]

jobs:
  sync-messages:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write # Required to create the PR

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Git User and Environment
        run: |
          git config user.name "civiform-github-automation"
          git config user.email "civiform-dev@exygy.com"
          echo "BRANCH_NAME=sync-i18n/$(date +%Y%m%d-%H%M%S)" >> $GITHUB_ENV

      - name: Sync Keys and Values to Language Files
        id: sync
        run: |
          # Use set -e for general failure detection
          set -e
          MESSAGES_FILE="server/conf/i18n/messages"
          
          # Function to extract, clean, and isolate keys for robust processing
          extract_keys() {
            # Use LC_ALL=C for reliable byte-level text processing to avoid encoding crashes.
            LC_ALL=C cat "$1" | \
            tr -cd '\11\12\15\40-\176\n' | \
            tr -d '\r' | \
            grep -E -v '^\s*#|^$' | \
            awk -F'=' '{print $1}' | \
            sed 's/\s*$//'
          }

          # Find all language files (messages.fr, messages.am, etc.) but exclude the base messages file and messages.en-US file.
          LANGUAGE_FILES=$(find server/conf/i18n -name 'messages.*' -type f | \
                           grep -v "${MESSAGES_FILE}$" | \
                           grep -v "messages.en-US$")

          if [ -z "$LANGUAGE_FILES" ]; then
            echo "No language files (messages.<lang>) found. Skipping sync."
            echo "changes_made=false" >> $GITHUB_OUTPUT
            exit 0
          fi

          # Store the content of the base messages file for later lookup
          MESSAGES_CONTENT=$(cat "${MESSAGES_FILE}")

          BASE_KEYS=$(extract_keys "${MESSAGES_FILE}")
          CHANGES=0

          for LANG_FILE in $LANGUAGE_FILES; do
            echo "Processing ${LANG_FILE}..."
            
            # Extract keys from the language file
            LANG_KEYS=$(extract_keys "${LANG_FILE}")
            
            # Find keys in base file that are NOT in language file
            NEW_KEYS=$(comm -23 <(echo "$BASE_KEYS" | sort) <(echo "$LANG_KEYS" | sort))

            if [ -z "$NEW_KEYS" ]; then
              echo "No new keys found for ${LANG_FILE}."
            else
              echo "New keys found for ${LANG_FILE}. Appending with values..."
              
              # Loop through each new key and find its corresponding line in the base file
              while read -r NEW_KEY; do
                # Use grep to find the full line in the base messages file
                # The -F flag treats the pattern as a fixed string, and -m 1 stops after the first match
                # Add `|| true` to prevent the script from failing if no match is found
                NEW_LINE=$(echo "$MESSAGES_CONTENT" | grep -F -m 1 "^${NEW_KEY}=" || true)
                
                # Append the new key-value pair to the language file
                if [ -n "$NEW_LINE" ]; then
                  echo "${NEW_LINE}" >> "${LANG_FILE}"
                fi
              done <<< "$NEW_KEYS"
              
              CHANGES=$((CHANGES + 1))
            fi
          done

          if [ $CHANGES -gt 0 ]; then
            echo "Total files updated: ${CHANGES}"
            echo "changes_made=true" >> $GITHUB_OUTPUT
          else
            echo "No changes needed for any language file."
            echo "changes_made=false" >> $GITHUB_OUTPUT
          fi
        shell: bash

      - name: Commit and Push Changes
        id: commit
        if: steps.sync.outputs.changes_made == 'true'
        run: |
          git checkout -b ${{ env.BRANCH_NAME }}
          git add server/conf/i18n/messages.*
          
          # Check for staged changes before committing to prevent failure
          if ! git diff-index --quiet --cached HEAD; then
            git commit -m "chore(i18n): Sync new keys and values from messages to messages.<lang> files"
            git push origin ${{ env.BRANCH_NAME }}
            echo "pr_needed=true" >> $GITHUB_OUTPUT
          else
            echo "No changes to commit. Skipping git commit and push."
            echo "pr_needed=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        if: steps.commit.outputs.pr_needed == 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_BODY="This PR was automatically created by the 'Sync New Keys to Translations' workflow to ensure all translation files contain the new keys and their values added to the base \`messages\` file.

          The new values from the base file are a starting point for translators. Please review the added entries and update the translations as needed."
          
          PR_URL=$(gh pr create \
            --head ${{ env.BRANCH_NAME }} \
            --base main \
            --title "chore(i18n): Sync new keys and values to translation files" \
            --body "$PR_BODY")
            
          echo "Created PR at ${PR_URL}"
